name: Setup Node.js Env

on:
  push:
    branches: [ "main" ]
    
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Docker Login
        run: docker login --username=jrinho22@gmail.com --password=Juninho22 
      - name: Herolu Login
        run: docker login --username=jrinho22@gmail.com --password=HRKU-91a2713f-17ce-409f-8085-7c6f3788acb9 registry.heroku.com
      - name: Disable Nx Daemon
        run: echo "NX_DAEMON=false" >> $GITHUB_ENV 
      - name: Build Docker image
        run: docker build -t chat-app . --tag registry.heroku.com/jrinho-chat-app-5/web
      - name: Push to registry
        run: docker push registry.heroku.com/jrinho-chat-app-5/web
      - name: release image
        run: heroku container:release web --app jrinho-chat-app-5
